// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_c-3GS8649s38GaoOJ58jOe0Bn8NeR3A',
    appId: '1:76578114467:web:c639665ba789cea4a9a816',
    messagingSenderId: '76578114467',
    projectId: 'realtime-quiz-wtg-v1-d7427',
    authDomain: 'realtime-quiz-wtg-v1-d7427.firebaseapp.com',
    storageBucket: 'realtime-quiz-wtg-v1-d7427.appspot.com',
    measurementId: 'G-6D0NNY0G82',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeQKdgcs_uv_1CVp3igcdPB59SKLazPOE',
    appId: '1:76578114467:android:bedd6f50d9d5cebaa9a816',
    messagingSenderId: '76578114467',
    projectId: 'realtime-quiz-wtg-v1-d7427',
    storageBucket: 'realtime-quiz-wtg-v1-d7427.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIKKH9f--78sic_VmbOWCzZT3fXfRbsys',
    appId: '1:76578114467:ios:c4f0e91742cf374da9a816',
    messagingSenderId: '76578114467',
    projectId: 'realtime-quiz-wtg-v1-d7427',
    storageBucket: 'realtime-quiz-wtg-v1-d7427.appspot.com',
    iosBundleId: 'com.example.realtimeQuiz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIKKH9f--78sic_VmbOWCzZT3fXfRbsys',
    appId: '1:76578114467:ios:7473469b9d96d955a9a816',
    messagingSenderId: '76578114467',
    projectId: 'realtime-quiz-wtg-v1-d7427',
    storageBucket: 'realtime-quiz-wtg-v1-d7427.appspot.com',
    iosBundleId: 'com.example.realtimeQuiz.RunnerTests',
  );
}
